<?php

namespace Dcat\Admin\Extension\Sku;

use Dcat\Admin\Extension;
use Illuminate\Console\Command;

class Sku extends Extension
{
    public $name = 'sku';

    public $views = __DIR__.'/../resources/views';

    public $assets = __DIR__.'/../resources/assets';
    public $composerJson = __DIR__.'/../composer.json';
    public $menu = [
        'title' => 'Sku',
        'path'  => 'sku',
        'icon'  => 'fa-gears',
    ];

    public function import(Command $command)
    {
        parent::import($command); // TODO: Change the autogenerated stub

        // 在这里写入你的导入逻辑

        $command->info('导入成功');
    }
}
